### ISSUE TITLE
working with another languages

### ISSUE THREAD

**Issue by mohammadsalmani28** [laravolt/avatar#84]
I want to use this package with another language like persian ....
when i used this i got some squares!!!
i think it has some problems with utf8 !!

**Comment by uyab** [comment]
Please check https://github.com/laravolt/avatar/issues/58

**Comment by mohammadsalmani28** [comment]
i used 'setFont' mehtod and it doesn't work!
i changed path in config/laravolt/avatar.php
but it doesn't work again! 
tnx for help!

**Comment by uyab** [comment]
hi @mohammadsalmani28 , sorry for slow response, would you check it again using the latest version?

**Comment by uyab** [comment]
https://github.com/laravolt/avatar/releases/tag/3.0.1

**Comment by uyab** [comment]
3.0.3 should fix this

**Comment by mohammadsalmani28** [comment]
now i test latest version but its looks like other and setBackground method has problem !

**Comment by uyab** [comment]
3.0.5 should (really) fix this 🙏

**Comment by mohammadsalmani28** [comment]
now problem of setBackground method fixed but font problem is still here!

**Comment by uyab** [comment]
Could you provide some sample code?

**Comment by mohammadsalmani28** [comment]
`$fake = Faker::name()->full;

$random = rand();

$avatar->create($fake)->setBackground('#FF3300')->setBorder(1, '#aabbcc')->save('storage/'.$random.'.png');
`

**Comment by mohammadsalmani28** [comment]
Any answer?!
@uyab
